lotto/urls.py
from django.conf.urls import url
from django.contrib import admin
from lotto import views

app_name = 'lotto'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^new/$', views.post, name='new_lotto'),
    url(r'^(?P<lottokey>[0-9]+)/detail/$', views.detail, name='detail'),

]

mysite/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from polls import views

urlpatterns = [
    url(r'^$', views.main, name = 'main'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')), # polls 앱에 신규로 만든 urls.py을  include 해준다.(연결)
    url(r'^lotto/', include('lotto.urls')),

]

polls/urls.py
# polls/urls
from django.conf.urls import url
from . import views

app_name = 'polls' #여러 앱을 사용할시 html의 url를 사용시 name의 이름이 다른 앱과 중복될수있다. 네임 스페이스의 중복을 맞기위하여 사용한다.
                   # index.html 에 {% url 'polls:detail' question.id  %} 이렇게 사용하여 다른 앱과의 네임스페이스 중복을 막는다.
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),

    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

lotto/models.py
from django.db import models
from django.utils import timezone
import random
# Create your models here.

class GuessNumber(models.Model):
    name = models.CharField(max_length =24)
    lottos = models.CharField(max_length = 255,default = '[1,2,3,4,5,6]')
    text = models.CharField(max_length = 255)
    num_lotto = models.IntegerField(default = 5)
    update_date = models.DateTimeField()

    #로또 번호 생성 및 데이터 베이스 저장
    def generate(self):
        self.lottos = ""
        origin = list(range(1,46))
        for _ in range(0, self.num_lotto):
            random.shuffle(origin)
            guess = origin[:6]
            guess.sort()
            self.lottos += str(guess) +'\n'
        self.update_date = timezone.now()
        self.save()
    def __str__(self):
        return "{} {} ".format(self.name,self.text)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField('date published')

    def __str__(self):
        return self.question_text

    def wqs_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question , on_delete=models.CASCADE)
    choice_test = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_test

lotto/forms.py
from django import forms
from .models import GuessNumber

class PostForm(forms.ModelForm):    # 폼을 입력받기위한 함수
    class Meta:
        model = GuessNumber
        fields = ('name','text',)
        

lotto/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import GuessNumber
from .forms import PostForm
# Create your views here.

def index(request):
    lottos = GuessNumber.objects.all()

    return render(request,"lotto/default.html",{"lottos" : lottos})

def post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            lotto = form.save(commit = False)
            lotto.generate()
            return redirect('lotto:index')
    else:
        form = PostForm()
        return render(request,"lotto/form.html" , {"form" : form})

def detail(request, lottokey):
    lotto = GuessNumber.objects.get(pk = lottokey)
    return render(request, "lotto/detail.html" , {"lotto" : lotto})

polls/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from django.http import HttpResponse , Http404
# Create your views here.
from .models import Question
from django.views import generic

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:6]


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # output = ",".join([q.question_text for q in latest_question_list])
#     context = {'latest_question_list' : latest_question_list}
#     return render(request, 'polls/index.html',context)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

# def detail(request,question_id):
#     # try:
#         # q = Question.objects.get(pk = question_id)
#     q = get_object_or_404(Question,pk = question_id)
#     # except Question.DoesNotExist:
#     return render(request, 'polls/detail.html', {'question': q})

# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'


def results(request,question_id):
    question = get_object_or_404(Question,pk = question_id)
    return render(request , 'polls/results.html',{'question' : question })


def vote(request,question_id):
    question = get_object_or_404(Question, pk = question_id)

    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
        # print("11111 :::: " , selected_choice)

    except:
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You111 didn't select a choice."
            })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return redirect('polls:results', question_id = question.id)

def main(request):
    return render(request, 'polls/main.html')
    

lotto/templates/lotto/default.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">
<head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel = "stylesheet" href="{% static 'css/lotto.css'%}"
</head>

<body>
  <div class="page-header">

  <h1>My Lotto Page</h1>
  <h2><a href = {% url 'lotto:new_lotto' %}>
    <span class = "glyphicon glyphicon-plus btn btn-default"></span>
  </h2>

  </div>


  <div class="container lotto">
    {% for lotto in lottos %}

    <h2><a href="{% url 'lotto:detail' lottokey=lotto.pk %}"> {{lotto.text}}</a></h2>
    <p> {{lotto.update_date}}</p>
    <p> {{lotto.lottos|linebreaksbr}}</p>

    {%endfor%}

  </div>
</body>
</html>

lotto/templates/lotto/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">
<head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/lotto.css'%}">
</head>

<body>
  <div class="page-header">
  <h1>My Lotto Page</h1>
  </div>
  <div class="container lotto">
    <h2>{{lotto.text}}</h2>
    <p> by {{lotto.name}}</p>
    <p> {{lotto.update_date}}</p>
    <p> {{lotto.lottos|linebreaksbr}}</p>
  </div>
</body>
</html>

lotto/templates/lotto/form.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="ko">
 <head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/lotto.css' %}">
 </head>
 <body>
  <div class="page-header">
   <h1>My Little New Lotto</h1>
  </div>
  <div class="container lotto">
   <form method="POST" class="post-form">
       {%csrf_token%}
       {{form.as_p}}
       <button type="submit" class="save btn btn-default">Save</button> </form>
  </div>
 </body>
</html>

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Django Polls Example</title>

  <!-- Bootstrap -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <span class="navbar-brand">Polls Example</span>
        </div>
        <ul class="nav navbar-nav">
          <li><a href = "{% url 'polls:index' %}">투표</a></li>
          <li><a href = "{% url 'lotto:index' %}">로또</a></li>
          <li class="navbar-right"><a href = "{% url 'admin:index' %}">관리자</a></li>
        </ul>
      </div>
    </nav>
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
  </html>

polls/templates/polls/detail.html
<h2> {{ question.question_text }} </h2>
{% if error_message %} <p> <strong> {{ error_message }} </p></strong> {% endif%}

<form action="{% url 'polls:vote' question.id %}" method = "POST">
    {%csrf_token%}
    {% for choice in question.choice_set.all %}
        <input type="radio" name = "choice" id="choice{{ forloop.counter }}"  value="{{ choice.id }}" />    <!-- 카운트 증가한다. -->
        <label for="choice{{forloop.counter}}" > {{ choice.choice_test}} </label><br/>
    {% endfor %}
    <input type = "submit" value = "투표" />
</form>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% if latest_question_list %}
     <ul>
     {% for question in latest_question_list %}
         <li><a href="{% url 'polls:detail' question.id  %}"> {{ question.question_text }} </a></li>
         <!--li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li-->
     {% endfor %}
     </ul>
{% else %}
     <p>No polls are available.</p>
{% endif %}
{% endblock content %}

polls/templates/polls/main.html
{% extends 'polls/base.html' %}

{% block content %}
    <!--
        ohter html here
    -->
{% endblock content %}

polls/templates/polls/results.html
<h1> {{ question.question_text}} </h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li> {{ choice.choice_test }}  -- {{ choice.votes}} </li>
    {% endfor %}

</ul>
<a href = "{% url 'polls:detail' question.id %}"> 다시 투표하기 </a>